[tool.poetry]
name = "photo-sorter"
version = "0.1.0"
description = ""
authors = ["Maarten Vermeulen <maartencvermeulen@yahoo.comix>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
